### ISSUE TITLE
Question about mask Observation

### ISSUE THREAD

**Issue by GoooDte** [anchen1011/FireAct#1]
Hello, thanks for your great work!
I see that you try to mask the `Observation` line in your [code](https://github.com/anchen1011/FireAct/blob/94c6189f04b10fccae6bcd97a4632d6119266899/finetune/llama_lora/finetune.py#L94), but the `mask` arg is set to `False` in your example of training with lora. Does this imply that in your experiments, not using masking performs better than using masking?
Looking forward to your reply!
Qiao

**Comment by anchen1011** [comment]
Hi Qiao, Sorry for the delayed reply. We did set mask arg to False during our training. However, it does not imply that not using masking performs better than using masking. 

We played with the masked / unmasked training a bit, but has not reached a solid conclusion.
