### ISSUE TITLE
How to make reflexion results on HotPotQA

### ISSUE THREAD

**Issue by pengjiao123** [anchen1011/FireAct#2]
Good work！

I want to know how the author did reflexion results  on hotpotqa.
I  have read the original author's method. His evaluator uses the ground truth to the questions in hotpotqa, and then uses em as an evaluation. I would like to ask you how to get the result of reflexion （Especially the evaluator） when doing comparative experiments.

Thanks for your reply

**Comment by pengjiao123** [comment]
Anothor two question

![image](https://github.com/anchen1011/FireAct/assets/24884878/8aafd015-2add-4d59-9a4a-a896c601a44b)
Is  Reflexion here generating samples using gpt-4 (we simply prompt for reflections at the 6th and 10th ReAct round?) and then fine-tuning the LLM ?

![image](https://github.com/anchen1011/FireAct/assets/24884878/7e9072a2-a130-4399-ae39-60d9fdc5adf2)

why are the temperatures different here? (Why not use 0 or 0.6 uniformly or do both experiments)

**Comment by anchen1011** [comment]
Hi there, sorry for the delayed reply. We apply reflexion when a solution is not reached at certain step. 

Is Reflexion here generating samples using gpt-4 (we simply prompt for reflections at the 6th and 10th ReAct round?) and then fine-tuning the LLM ? 
Yes

why are the temperatures different here? (Why not use 0 or 0.6 uniformly or do both experiments)
Thanks for the suggestion. We will look into these details and see if we can experiment with both settings.
